// src/email/email.controller.ts
import { Controller, Post, Body, UsePipes, ValidationPipe, HttpCode, HttpStatus } from '@nestjs/common';
import { ApiTags, ApiOperation, ApiResponse, ApiBody } from '@nestjs/swagger';
import { EmailService } from './email.service';
import { SendEmailDto, EmailType } from './dto/send-email.dto';

/**
 * Controller for handling email-related requests.
 * 
 * @remarks
 * - Provides endpoints for sending various types of emails (welcome, password reset, receipts, newsletters).
 * - Uses ValidationPipe to ensure incoming data is valid (class-validator).
 * - All endpoints return HTTP 202 (Accepted) to indicate the email was queued/sent asynchronously.
 * - GDPR compliant: does not log raw email content, only metadata.
 * - i18n ready: metadata can include locale for future template translations.
 * - Multi-currency ready: payment receipts accept currency codes via metadata.
 */
@ApiTags('Email')
@Controller('email')
export class EmailController {
  constructor(private readonly emailService: EmailService) {}

  /**
   * Generic endpoint to send any type of email.
   * 
   * @param dto - The SendEmailDto containing recipient, type, content, and metadata.
   * @returns A confirmation message.
   */
  @Post('send')
  @HttpCode(HttpStatus.ACCEPTED)
  @ApiOperation({ 
    summary: 'Send any type of email',
    description: 'Accepts a SendEmailDto and dispatches the email based on the type field.'
  })
  @ApiBody({ type: SendEmailDto })
  @ApiResponse({ status: 202, description: 'Email accepted for sending.' })
  @ApiResponse({ status: 400, description: 'Validation error (invalid email, missing fields, etc.).' })
  @UsePipes(new ValidationPipe({ transform: true, whitelist: true }))
  async send(@Body() dto: SendEmailDto): Promise<{ message: string; to: string; type: EmailType }> {
    await this.emailService.send(dto);
    return {
      message: 'Email accepted and will be sent shortly',
      to: dto.to,
      type: dto.type,
    };
  }

  /**
   * Convenience endpoint for sending a welcome email.
   * 
   * @param to - Recipient email address.
   * @param userName - User's full name.
   */
  @Post('welcome')
  @HttpCode(HttpStatus.ACCEPTED)
  @ApiOperation({ summary: 'Send a welcome email' })
  @ApiResponse({ status: 202, description: 'Welcome email accepted.' })
  @ApiResponse({ status: 400, description: 'Invalid email or missing user name.' })
  @UsePipes(new ValidationPipe({ transform: true }))
  async sendWelcome(
    @Body('to') to: string,
    @Body('userName') userName: string,
  ): Promise<{ message: string }> {
    await this.emailService.sendWelcomeEmail(to, userName);
    return { message: `Welcome email sent to ${to}` };
  }

  /**
   * Convenience endpoint for sending a password reset email.
   * 
   * @param to - Recipient email address.
   * @param userName - User's full name.
   * @param resetLink - Password reset link (generated by the auth service).
   */
  @Post('reset-password')
  @HttpCode(HttpStatus.ACCEPTED)
  @ApiOperation({ summary: 'Send a password reset email' })
  @ApiResponse({ status: 202, description: 'Password reset email accepted.' })
  @ApiResponse({ status: 400, description: 'Invalid email or missing required fields.' })
  @UsePipes(new ValidationPipe({ transform: true }))
  async sendPasswordReset(
    @Body('to') to: string,
    @Body('userName') userName: string,
    @Body('resetLink') resetLink: string,
  ): Promise<{ message: string }> {
    await this.emailService.sendPasswordResetEmail(to, userName, resetLink);
    return { message: `Password reset email sent to ${to}` };
  }

  /**
   * Convenience endpoint for sending a payment receipt.
   * 
   * @param to - Recipient email address.
   * @param userName - User's full name.
   * @param orderId - Order or transaction ID.
   * @param amount - Payment amount (supports multi-currency).
   * @param currency - Currency code (e.g., 'ETB', 'USD', 'EUR').
   */
  @Post('receipt')
  @HttpCode(HttpStatus.ACCEPTED)
  @ApiOperation({ summary: 'Send a payment receipt email' })
  @ApiResponse({ status: 202, description: 'Payment receipt email accepted.' })
  @ApiResponse({ status: 400, description: 'Invalid input.' })
  @UsePipes(new ValidationPipe({ transform: true }))
  async sendReceipt(
    @Body('to') to: string,
    @Body('userName') userName: string,
    @Body('orderId') orderId: string,
    @Body('amount') amount: number,
    @Body('currency') currency: string = 'ETB',
  ): Promise<{ message: string }> {
    await this.emailService.sendPaymentReceipt(to, userName, orderId, amount, currency);
    return { message: `Payment receipt sent to ${to}` };
  }

  /**
   * Convenience endpoint for sending a periodic newsletter.
   * 
   * @param to - Recipient email address.
   * @param userName - Subscriber's name.
   */
  @Post('newsletter')
  @HttpCode(HttpStatus.ACCEPTED)
  @ApiOperation({ summary: 'Send a periodic newsletter' })
  @ApiResponse({ status: 202, description: 'Newsletter email accepted.' })
  @ApiResponse({ status: 400, description: 'Invalid email.' })
  @UsePipes(new ValidationPipe({ transform: true }))
  async sendNewsletter(
    @Body('to') to: string,
    @Body('userName') userName: string,
  ): Promise<{ message: string }> {
    await this.emailService.sendNewsletter(to, userName);
    return { message: `Newsletter sent to ${to}` };
  }
}
