import { Controller, Post, Get, Body, Param, UseGuards } from '@nestjs/common';
import { ApiBearerAuth, ApiOperation, ApiTags, ApiConsumes, ApiBody } from '@nestjs/swagger';
import { KycService } from './kyc.service';
import { JwtAuthGuard } from '../../common/guards/jwt-auth.guard';
import { RolesGuard } from '../../common/guards/roles.guard';
import { Roles } from '../../common/decorators/roles.decorator';
import { CurrentUser, CurrentUserPayload } from '../../common/decorators/current-user.decorator';
import { SubmitKycDto } from './dto/submit-kyc.dto';
import { RejectKycDto } from './dto/reject-kyc.dto';

/**
 * Exposes REST endpoints for Know Your Customer (KYC) verification workflows.
 *
 * Responsibilities:
 * - Generate ephemeral presigned S3 upload URLs for client uploads.
 * - Accept secure, pre-uploaded identity tracking references.
 * - Provide verification status for authenticated users.
 * - Allow administrators to manage, review, approve, or reject submissions.
 *
 * Security:
 * - Requires JWT authentication for all endpoints.
 * - Restricts administrative operations using role-based access control.
 *
 * @controller KycController
 */
@ApiTags('kyc')
@ApiBearerAuth()
@UseGuards(JwtAuthGuard, RolesGuard) // Clean fix: Stack both guards globally at controller level so pipeline execution sequence is consistent
@Controller('kyc')
export class KycController {
  /**
   * Creates a new KYC controller instance.
   *
   * @param kycService Service responsible for KYC verification workflows.
   */
  constructor(private readonly kycService: KycService) {}

  /**
   * Generates secure presigned S3 upload paths allowing the Next.js client
   * to push assets directly to private cloud buckets.
   *
   * This implements high-performance, direct-to-cloud upload architecture
   * to shield the server from parsing heavy file byte streams.
   */
  @Get('upload-urls')
  @ApiOperation({ summary: 'Acquire ephemeral presigned upload URLs for identity artifacts' })
  async getUploadUrls(@CurrentUser() user: CurrentUserPayload) {
    return this.kycService.createPresignedUploadTokens(user.userId);
  }

  /**
   * Submits pre-uploaded cloud storage tracking keys for processing.
   *
   * Workflow:
   * 1. Validate storage paths exist via global class-validator DTO pipelines.
   * 2. Pass references to underlying biometrics verification handlers.
   *
   * @param user Authenticated user information.
   * @param dto Verification submission payload holding S3 string references.
   *
   * @returns Verification result generated by the KYC service.
   */
  @Post('submit')
  @ApiConsumes('application/json')
  @ApiOperation({ summary: 'Submit pre-uploaded storage references for biometric identity checks' })
  async submitKyc(@CurrentUser() user: CurrentUserPayload, @Body() dto: SubmitKycDto) {
    // Clean fix: Removed manual if-condition checks. Class-validator pipes on SubmitKycDto reject early automatically.
    return this.kycService.submitVerification(user.userId, dto);
  }

  /**
   * Retrieves the authenticated user's KYC verification status.
   *
   * @param user Authenticated user information.
   *
   * @returns Current verification record and status.
   */
  @Get('status')
  @ApiOperation({ summary: 'Check current KYC verification status and records' })
  async getStatus(@CurrentUser() user: CurrentUserPayload) {
    return this.kycService.getVerificationStatus(user.userId);
  }

  /**
   * Retrieves all pending verification requests.
   *
   * This endpoint is restricted to administrators and is intended
   * for manual review workflows.
   *
   * @returns Collection of pending verification records.
   */
  @Get('admin/pending')
  @Roles('ADMIN')
  @ApiOperation({ summary: 'List all pending KYC submissions (Admin only)' })
  async getPending() {
    return this.kycService.getPendingVerifications();
  }

  /**
   * Approves a pending KYC verification request.
   *
   * This endpoint is restricted to administrators.
   *
   * @param id Verification identifier.
   * @param admin Authenticated administrator information.
   *
   * @returns Updated verification record.
   */
  @Post('admin/approve/:id')
  @Roles('ADMIN')
  @ApiOperation({ summary: 'Approve a pending KYC submission (Admin only)' })
  async approve(@Param('id') id: string, @CurrentUser() admin: CurrentUserPayload) {
    return this.kycService.approveVerification(id, admin.userId);
  }

  /**
   * Rejects a pending KYC verification request.
   *
   * This endpoint is restricted to administrators.
   *
   * @param id Verification identifier.
   * @param admin Authenticated administrator information.
   * @param dto Rejection payload containing the rejection reason.
   *
   * @returns Updated verification record.
   */
  @Post('admin/reject/:id')
  @Roles('ADMIN')
  @ApiBody({ type: RejectKycDto }) // Clean fix: Added explicit API model binding to map parameters cleanly onto your OpenAPI spec layout
  @ApiOperation({ summary: 'Reject a pending KYC submission (Admin only)' })
  async reject(
    @Param('id') id: string,
    @CurrentUser() admin: CurrentUserPayload,
    @Body() dto: RejectKycDto,
  ) {
    return this.kycService.rejectVerification(id, admin.userId, dto.reason);
  }
}
