import { Injectable, Logger } from '@nestjs/common';
import type { Candidate } from '../interfaces/candidate.interface';
import type { Sanitizer } from '../interfaces/sanitizer.interface';
import type { LlmCandidateProfile } from '../interfaces/llm-candidate-profile.interface';
import type { CandidateTokenMapping } from '../interfaces/candidate-token-mapping.interface';
import { generateOpaqueToken } from '../utils/token-generator.util';
import {
  containsPotentialPii,
  detectEmail,
  detectPhone,
  detectUrl,
} from '../utils/pii-detector.util';

const REDACTED = '[REDACTED]';

/** A single entry in the GDPR audit trail. */
export interface SanitizerAuditEntry {
  readonly timestamp: Date;
  readonly freelancerId: string;
  readonly sessionToken: string;
  readonly piiDetected: boolean;
  readonly piiCategories: readonly string[];
  readonly fieldsRedacted: readonly string[];
  readonly confirmedPiiFree: boolean;
}

/**
 * GDPR boundary service.
 *
 * Transforms raw Candidate data into LlmCandidateProfile (PII-free, LLM-safe)
 * and stores internal CandidateTokenMapping for later resolution.
 *
 * Implements the Sanitizer interface — token mappings are stored in-memory
 * and retrievable via getMapping() / getAllMappings().
 * Maintains a full GDPR audit trail of every sanitization event.
 */
@Injectable()
export class SanitizerService implements Sanitizer {
  private readonly logger = new Logger(SanitizerService.name);
  private readonly tokenMappings = new Map<string, CandidateTokenMapping>();
  private readonly auditLog: SanitizerAuditEntry[] = [];

  async sanitize(candidate: Candidate): Promise<LlmCandidateProfile> {
    const sessionToken = generateOpaqueToken('candidate');

    const mapping: CandidateTokenMapping = {
      sessionToken,
      freelancerId: candidate.freelancerId,
    };
    this.tokenMappings.set(sessionToken, mapping);

    const bioRedacted = this.redactIfPii(candidate.bio);
    const projectsRedacted = candidate.pastProjects.map((p) =>
      this.redactIfPii(`${p.title}: ${p.description}`),
    );

    const piiCategories = this.detectPiiCategories(candidate);
    const fieldsRedacted = this.detectRedactedFields(candidate, bioRedacted, projectsRedacted);
    const piiDetected = piiCategories.length > 0;

    const entry: SanitizerAuditEntry = {
      timestamp: new Date(),
      freelancerId: candidate.freelancerId,
      sessionToken,
      piiDetected,
      piiCategories,
      fieldsRedacted,
      confirmedPiiFree: !piiDetected,
    };
    this.auditLog.push(entry);
    this.logger.log(
      `GDPR sanitize — ${candidate.freelancerId} → ${sessionToken}, PII: ${piiDetected}`,
    );

    return {
      sessionToken,
      title: candidate.title,
      bioSummary: bioRedacted,
      skills: candidate.skills,
      experienceYears: candidate.experienceYears,
      pastProjectsSummary: projectsRedacted,
    };
  }

  async sanitizeBatch(candidates: readonly Candidate[]): Promise<readonly LlmCandidateProfile[]> {
    return Promise.all(candidates.map((c) => this.sanitize(c)));
  }

  /**
   * Retrieve the internal token mapping for a given session token.
   *
   * @param sessionToken - The opaque token used in LLM requests.
   * @returns The mapping containing the real freelancer ID, or undefined.
   */
  getMapping(sessionToken: string): CandidateTokenMapping | undefined {
    return this.tokenMappings.get(sessionToken);
  }

  /**
   * Retrieve all internal token mappings generated by this service instance.
   * Useful for batch resolution after sanitizeBatch completes.
   */
  getAllMappings(): readonly CandidateTokenMapping[] {
    return [...this.tokenMappings.values()];
  }

  /**
   * Return a read-only snapshot of the GDPR audit trail.
   * Ordered newest-first.
   */
  getAuditLog(): readonly SanitizerAuditEntry[] {
    return [...this.auditLog].reverse();
  }

  /**
   * Detect which PII categories are present in a candidate.
   */
  private detectPiiCategories(candidate: Candidate): string[] {
    const categories: string[] = [];
    const texts = [
      candidate.bio,
      ...candidate.pastProjects.map((p) => `${p.title}: ${p.description}`),
    ];
    for (const t of texts) {
      if (detectEmail(t)) {
        categories.push('email');
        break;
      }
    }
    for (const t of texts) {
      if (detectPhone(t)) {
        categories.push('phone');
        break;
      }
    }
    for (const t of texts) {
      if (detectUrl(t)) {
        categories.push('url');
        break;
      }
    }
    return categories;
  }

  /**
   * Determine which fields were redacted after sanitization.
   */
  private detectRedactedFields(
    candidate: Candidate,
    bioRedacted: string,
    projectSummaries: string[],
  ): string[] {
    const fields: string[] = [];
    if (bioRedacted === REDACTED) fields.push('bio');
    for (let i = 0; i < projectSummaries.length; i++) {
      if (projectSummaries[i] === REDACTED) fields.push(`pastProjects[${i}]`);
    }
    return fields;
  }

  /**
   * Redact a text field if it contains potential PII.
   * PII detection uses regex patterns for email, phone, and URL.
   *
   * @param text - The text to inspect.
   * @returns The original text if clean, or [REDACTED] if PII is detected.
   */
  private redactIfPii(text: string): string {
    return containsPotentialPii(text) ? REDACTED : text;
  }
}
